# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Post',
        ),
    ]
