# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='post'),
            preserve_default=False,
        ),
    ]
