# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dp',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
